"""empty message

Revision ID: e1f04fd14ff6
Revises: 61cba5fde5c1
Create Date: 2024-09-13 13:54:25.198228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f04fd14ff6'
down_revision = '61cba5fde5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('Terrain', sa.String(length=50), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Terrain'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('population')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('Cost_in_Credits', sa.Integer(), nullable=False),
    sa.Column('Crew', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Cost_in_Credits'),
    sa.UniqueConstraint('Crew'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('vehicles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicles_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_eye_color_key', type_='unique')
        batch_op.drop_constraint('characters_gender_key', type_='unique')
        batch_op.drop_constraint('characters_hair_color_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_hair_color_key', ['hair_color'])
        batch_op.create_unique_constraint('characters_gender_key', ['gender'])
        batch_op.create_unique_constraint('characters_eye_color_key', ['eye_color'])

    op.drop_table('favourites')
    op.drop_table('vehicles')
    op.drop_table('planets')
    # ### end Alembic commands ###
